- hosts: all
  vars:
    packages:
      - tree
      - apache2
      - wget
      - git
      - unzip
  become: yes
  tasks:
  - name: install apache
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present